package com.czp.project.dao;

import com.czp.project.common.bean.BasePower;
import com.czp.project.common.bean.BasePowerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    long countByExample(BasePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int deleteByExample(BasePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int insert(BasePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int insertSelective(BasePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    List<BasePower> selectByExample(BasePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    BasePower selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasePower record, @Param("example") BasePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int updateByExample(@Param("record") BasePower record, @Param("example") BasePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int updateByPrimaryKeySelective(BasePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    int updateByPrimaryKey(BasePower record);
  //更新user里面的权限id
    int updateUserRole(@Param("roleId1")String roleId1, @Param("roleId2")int roleId2);
}