package com.czp.project.dao;

import com.czp.project.common.bean.Cost;
import com.czp.project.common.bean.CostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    long countByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insertSelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    List<Cost> selectByExample(CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExample(@Param("record") Cost record, @Param("example") CostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKeySelective(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKey(Cost record);
}