package com.czp.project.dao;

import com.czp.project.common.bean.FamilyMembers;
import com.czp.project.common.bean.FamilyMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FamilyMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    long countByExample(FamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int deleteByExample(FamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int insert(FamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int insertSelective(FamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    List<FamilyMembers> selectByExample(FamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    FamilyMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") FamilyMembers record, @Param("example") FamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int updateByExample(@Param("record") FamilyMembers record, @Param("example") FamilyMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int updateByPrimaryKeySelective(FamilyMembers record);
    void updateBytelphone(FamilyMembers familyMembers);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    int updateByPrimaryKey(FamilyMembers record);
}