package com.czp.project.dao;

import com.czp.project.common.bean.Index;
import com.czp.project.common.bean.IndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    long countByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insert(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insertSelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    List<Index> selectByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    Index selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Index record, @Param("example") IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExample(@Param("record") Index record, @Param("example") IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKeySelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKey(Index record);
}