package com.czp.project.dao;

import com.czp.project.common.bean.Modular;
import com.czp.project.common.bean.ModularExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModularMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    long countByExample(ModularExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByExample(ModularExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insert(Modular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insertSelective(Modular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    List<Modular> selectByExample(ModularExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    Modular selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Modular record, @Param("example") ModularExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExample(@Param("record") Modular record, @Param("example") ModularExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKeySelective(Modular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modular
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKey(Modular record);
}