package com.czp.project.dao;

import com.czp.project.common.bean.Monitor;
import com.czp.project.common.bean.MonitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    long countByExample(MonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByExample(MonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insert(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insertSelective(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    List<Monitor> selectByExample(MonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    Monitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Monitor record, @Param("example") MonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExample(@Param("record") Monitor record, @Param("example") MonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKeySelective(Monitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKey(Monitor record);
}