package com.czp.project.dao;

import com.czp.project.common.bean.OldManLeave;
import com.czp.project.common.bean.OldManLeaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OldManLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    long countByExample(OldManLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByExample(OldManLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insert(OldManLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int insertSelective(OldManLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    List<OldManLeave> selectByExample(OldManLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    OldManLeave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") OldManLeave record, @Param("example") OldManLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByExample(@Param("record") OldManLeave record, @Param("example") OldManLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKeySelective(OldManLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    int updateByPrimaryKey(OldManLeave record);
}