package com.czp.project.dao;

import com.czp.project.common.bean.OmQingjia;
import com.czp.project.common.bean.OmQingjiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmQingjiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    long countByExample(OmQingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int deleteByExample(OmQingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int insert(OmQingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int insertSelective(OmQingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    List<OmQingjia> selectByExample(OmQingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    OmQingjia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") OmQingjia record, @Param("example") OmQingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int updateByExample(@Param("record") OmQingjia record, @Param("example") OmQingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int updateByPrimaryKeySelective(OmQingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man_leave
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    int updateByPrimaryKey(OmQingjia record);
}