package com.czp.project.dao;

import com.czp.project.common.bean.OmZhuanfang;
import com.czp.project.common.bean.OmZhuanfangExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmZhuanfangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    long countByExample(OmZhuanfangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int deleteByExample(OmZhuanfangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int insert(OmZhuanfang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int insertSelective(OmZhuanfang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    List<OmZhuanfang> selectByExample(OmZhuanfangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    OmZhuanfang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") OmZhuanfang record, @Param("example") OmZhuanfangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int updateByExample(@Param("record") OmZhuanfang record, @Param("example") OmZhuanfangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int updateByPrimaryKeySelective(OmZhuanfang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_zhuangfang
     *
     * @mbg.generated Fri May 01 11:46:22 CST 2020
     */
    int updateByPrimaryKey(OmZhuanfang record);
}