package com.czp.project.dao;

import com.czp.project.common.bean.UserLeave;
import com.czp.project.common.bean.UserLeaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    long countByExample(UserLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int deleteByExample(UserLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int insert(UserLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int insertSelective(UserLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    List<UserLeave> selectByExample(UserLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    UserLeave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserLeave record, @Param("example") UserLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int updateByExample(@Param("record") UserLeave record, @Param("example") UserLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int updateByPrimaryKeySelective(UserLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_leave
     *
     * @mbg.generated Thu May 07 18:51:13 CST 2020
     */
    int updateByPrimaryKey(UserLeave record);
}