package com.czp.project.common.bean;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.card_numb
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer cardNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.balance
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.oldman_id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer oldmanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.card_numb
     *
     * @return the value of account.card_numb
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getCardNumb() {
        return cardNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.card_numb
     *
     * @param cardNumb the value for account.card_numb
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setCardNumb(Integer cardNumb) {
        this.cardNumb = cardNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.balance
     *
     * @return the value of account.balance
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.balance
     *
     * @param balance the value for account.balance
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.oldman_id
     *
     * @return the value of account.oldman_id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getOldmanId() {
        return oldmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.oldman_id
     *
     * @param oldmanId the value for account.oldman_id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setOldmanId(Integer oldmanId) {
        this.oldmanId = oldmanId;
    }
}