package com.czp.project.common.bean;

import java.io.Serializable;

public class BaseUser  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.user_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String userImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.user_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.password
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.salary
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Double salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.work_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String workTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.title
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user_info.role_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private BasePower role;
    public BaseUser(Integer id, String userImg, String userName, String password, Double salary, String workTime) {
		super();
		this.id = id;
		this.userImg = userImg;
		this.userName = userName;
		this.password = password;
		this.salary = salary;
		this.workTime = workTime;
	}
    
    public BaseUser() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.id
     *
     * @return the value of base_user_info.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    
    public Integer getId() {
        return id;
    }

   

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.id
     *
     * @param id the value for base_user_info.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.user_img
     *
     * @return the value of base_user_info.user_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.user_img
     *
     * @param userImg the value for base_user_info.user_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.user_name
     *
     * @return the value of base_user_info.user_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.user_name
     *
     * @param userName the value for base_user_info.user_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.password
     *
     * @return the value of base_user_info.password
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.password
     *
     * @param password the value for base_user_info.password
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.salary
     *
     * @return the value of base_user_info.salary
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.salary
     *
     * @param salary the value for base_user_info.salary
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.work_time
     *
     * @return the value of base_user_info.work_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.work_time
     *
     * @param workTime the value for base_user_info.work_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setWorkTime(String workTime) {
        this.workTime = workTime == null ? null : workTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user_info.title
     *
     * @return the value of base_user_info.title
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user_info.title
     *
     * @param title the value for base_user_info.title
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

	public BasePower getRole() {
		return role;
	}

	public void setRole(BasePower role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "BaseUser [id=" + id + ", userImg=" + userImg + ", userName=" + userName + ", password=" + password
				+ ", salary=" + salary + ", workTime=" + workTime + ", title=" + title + ", role=" + role + "]";
	}

   
    
}