package com.czp.project.common.bean;

public class BasePower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.id
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    private String power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.p_desc
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    private String pDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.id
     *
     * @return the value of power.id
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.id
     *
     * @param id the value for power.id
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.power
     *
     * @return the value of power.power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.power
     *
     * @param power the value for power.power
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.p_desc
     *
     * @return the value of power.p_desc
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.p_desc
     *
     * @param pDesc the value for power.p_desc
     *
     * @mbg.generated Thu Apr 30 16:48:58 CST 2020
     */
    public void setpDesc(String pDesc) {
        this.pDesc = pDesc == null ? null : pDesc.trim();
    }
}