package com.czp.project.common.bean;

public class Charges {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charges.id
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charges.index_name
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charges.amount_of_money
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    private Integer amountOfMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charges.unit
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charges.id
     *
     * @return the value of charges.id
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charges.id
     *
     * @param id the value for charges.id
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charges.index_name
     *
     * @return the value of charges.index_name
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charges.index_name
     *
     * @param indexName the value for charges.index_name
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charges.amount_of_money
     *
     * @return the value of charges.amount_of_money
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public Integer getAmountOfMoney() {
        return amountOfMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charges.amount_of_money
     *
     * @param amountOfMoney the value for charges.amount_of_money
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public void setAmountOfMoney(Integer amountOfMoney) {
        this.amountOfMoney = amountOfMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charges.unit
     *
     * @return the value of charges.unit
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charges.unit
     *
     * @param unit the value for charges.unit
     *
     * @mbg.generated Mon Apr 27 20:58:09 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

	@Override
	public String toString() {
		return "Charges [id=" + id + ", indexName=" + indexName + ", amountOfMoney=" + amountOfMoney + ", unit=" + unit
				+ "]";
	}
    
}