package com.czp.project.common.bean;

public class Cost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.balance
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer indexId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.id
     *
     * @return the value of cost.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.id
     *
     * @param id the value for cost.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.balance
     *
     * @return the value of cost.balance
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.balance
     *
     * @param balance the value for cost.balance
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.index_id
     *
     * @return the value of cost.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.index_id
     *
     * @param indexId the value for cost.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }
}