package com.czp.project.common.bean;

public class FamilyMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.family_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String familyImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.family_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.address
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.id
     *
     * @return the value of family_members.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.id
     *
     * @param id the value for family_members.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.family_img
     *
     * @return the value of family_members.family_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getFamilyImg() {
        return familyImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.family_img
     *
     * @param familyImg the value for family_members.family_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setFamilyImg(String familyImg) {
        this.familyImg = familyImg == null ? null : familyImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.family_name
     *
     * @return the value of family_members.family_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.family_name
     *
     * @param familyName the value for family_members.family_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.telphone
     *
     * @return the value of family_members.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.telphone
     *
     * @param telphone the value for family_members.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.address
     *
     * @return the value of family_members.address
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.address
     *
     * @param address the value for family_members.address
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}