package com.czp.project.common.bean;

public class FamilyMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.id
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.family_password
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    private String familyPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.family_name
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.telphone
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.address
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.id
     *
     * @return the value of family_members.id
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.id
     *
     * @param id the value for family_members.id
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.family_password
     *
     * @return the value of family_members.family_password
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public String getFamilyPassword() {
        return familyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.family_password
     *
     * @param familyPassword the value for family_members.family_password
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public void setFamilyPassword(String familyPassword) {
        this.familyPassword = familyPassword == null ? null : familyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.family_name
     *
     * @return the value of family_members.family_name
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.family_name
     *
     * @param familyName the value for family_members.family_name
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.telphone
     *
     * @return the value of family_members.telphone
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.telphone
     *
     * @param telphone the value for family_members.telphone
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.address
     *
     * @return the value of family_members.address
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.address
     *
     * @param address the value for family_members.address
     *
     * @mbg.generated Wed May 13 14:27:50 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

	@Override
	public String toString() {
		return "FamilyMembers [id=" + id + ", familyPassword=" + familyPassword + ", familyName=" + familyName
				+ ", telphone=" + telphone + ", address=" + address + "]";
	}
    
}