package com.czp.project.common.bean;

public class Index {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_name
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.amount_of_money
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private Integer amountOfMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.unit
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.id
     *
     * @return the value of index.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.id
     *
     * @param id the value for index.id
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_name
     *
     * @return the value of index.index_name
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_name
     *
     * @param indexName the value for index.index_name
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.amount_of_money
     *
     * @return the value of index.amount_of_money
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public Integer getAmountOfMoney() {
        return amountOfMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.amount_of_money
     *
     * @param amountOfMoney the value for index.amount_of_money
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setAmountOfMoney(Integer amountOfMoney) {
        this.amountOfMoney = amountOfMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.unit
     *
     * @return the value of index.unit
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.unit
     *
     * @param unit the value for index.unit
     *
     * @mbg.generated Sat Apr 11 20:55:49 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}