package com.czp.project.common.bean;

public class Index {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String indexName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.id
     *
     * @return the value of index.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.id
     *
     * @param id the value for index.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_name
     *
     * @return the value of index.index_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_name
     *
     * @param indexName the value for index.index_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }
}