package com.czp.project.common.bean;

public class Modular {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modular.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modular.name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modular.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modular.id
     *
     * @return the value of modular.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modular.id
     *
     * @param id the value for modular.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modular.name
     *
     * @return the value of modular.name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modular.name
     *
     * @param name the value for modular.name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modular.description
     *
     * @return the value of modular.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modular.description
     *
     * @param description the value for modular.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}