package com.czp.project.common.bean;

import java.util.Date;

public class Monitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.exam_time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private Date examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.level
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.old_man_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private Integer oldManId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.user_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.id
     *
     * @return the value of monitor.id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.id
     *
     * @param id the value for monitor.id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.exam_time
     *
     * @return the value of monitor.exam_time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public Date getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.exam_time
     *
     * @param examTime the value for monitor.exam_time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.level
     *
     * @return the value of monitor.level
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.level
     *
     * @param level the value for monitor.level
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.old_man_id
     *
     * @return the value of monitor.old_man_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public Integer getOldManId() {
        return oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.old_man_id
     *
     * @param oldManId the value for monitor.old_man_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setOldManId(Integer oldManId) {
        this.oldManId = oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.user_id
     *
     * @return the value of monitor.user_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.user_id
     *
     * @param userId the value for monitor.user_id
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.time
     *
     * @return the value of monitor.time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.time
     *
     * @param time the value for monitor.time
     *
     * @mbg.generated Wed May 06 21:52:29 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}