package com.czp.project.common.bean;

public class Monitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.level
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer oldManId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer indexId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.id
     *
     * @return the value of monitor.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.id
     *
     * @param id the value for monitor.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.description
     *
     * @return the value of monitor.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.description
     *
     * @param description the value for monitor.description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.level
     *
     * @return the value of monitor.level
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.level
     *
     * @param level the value for monitor.level
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.old_man_id
     *
     * @return the value of monitor.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getOldManId() {
        return oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.old_man_id
     *
     * @param oldManId the value for monitor.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setOldManId(Integer oldManId) {
        this.oldManId = oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.user_id
     *
     * @return the value of monitor.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.user_id
     *
     * @param userId the value for monitor.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.index_id
     *
     * @return the value of monitor.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.index_id
     *
     * @param indexId the value for monitor.index_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setIndexId(Integer indexId) {
        this.indexId = indexId;
    }
}