package com.czp.project.common.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OldManRuZhuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public OldManRuZhuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andUserLogIsNull() {
            addCriterion("user_log is null");
            return (Criteria) this;
        }

        public Criteria andUserLogIsNotNull() {
            addCriterion("user_log is not null");
            return (Criteria) this;
        }

        public Criteria andUserLogEqualTo(String value) {
            addCriterion("user_log =", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotEqualTo(String value) {
            addCriterion("user_log <>", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogGreaterThan(String value) {
            addCriterion("user_log >", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogGreaterThanOrEqualTo(String value) {
            addCriterion("user_log >=", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLessThan(String value) {
            addCriterion("user_log <", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLessThanOrEqualTo(String value) {
            addCriterion("user_log <=", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogLike(String value) {
            addCriterion("user_log like", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotLike(String value) {
            addCriterion("user_log not like", value, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogIn(List<String> values) {
            addCriterion("user_log in", values, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotIn(List<String> values) {
            addCriterion("user_log not in", values, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogBetween(String value1, String value2) {
            addCriterion("user_log between", value1, value2, "userLog");
            return (Criteria) this;
        }

        public Criteria andUserLogNotBetween(String value1, String value2) {
            addCriterion("user_log not between", value1, value2, "userLog");
            return (Criteria) this;
        }

        public Criteria andInRoomIdIsNull() {
            addCriterion("in_room_id is null");
            return (Criteria) this;
        }

        public Criteria andInRoomIdIsNotNull() {
            addCriterion("in_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andInRoomIdEqualTo(String value) {
            addCriterion("in_room_id =", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdNotEqualTo(String value) {
            addCriterion("in_room_id <>", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdGreaterThan(String value) {
            addCriterion("in_room_id >", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdGreaterThanOrEqualTo(String value) {
            addCriterion("in_room_id >=", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdLessThan(String value) {
            addCriterion("in_room_id <", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdLessThanOrEqualTo(String value) {
            addCriterion("in_room_id <=", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdLike(String value) {
            addCriterion("in_room_id like", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdNotLike(String value) {
            addCriterion("in_room_id not like", value, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdIn(List<String> values) {
            addCriterion("in_room_id in", values, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdNotIn(List<String> values) {
            addCriterion("in_room_id not in", values, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdBetween(String value1, String value2) {
            addCriterion("in_room_id between", value1, value2, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andInRoomIdNotBetween(String value1, String value2) {
            addCriterion("in_room_id not between", value1, value2, "inRoomId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdIsNull() {
            addCriterion("oldman_id is null");
            return (Criteria) this;
        }

        public Criteria andOldmanIdIsNotNull() {
            addCriterion("oldman_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldmanIdEqualTo(Integer value) {
            addCriterion("oldman_id =", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdNotEqualTo(Integer value) {
            addCriterion("oldman_id <>", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdGreaterThan(Integer value) {
            addCriterion("oldman_id >", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("oldman_id >=", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdLessThan(Integer value) {
            addCriterion("oldman_id <", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdLessThanOrEqualTo(Integer value) {
            addCriterion("oldman_id <=", value, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdIn(List<Integer> values) {
            addCriterion("oldman_id in", values, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdNotIn(List<Integer> values) {
            addCriterion("oldman_id not in", values, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdBetween(Integer value1, Integer value2) {
            addCriterion("oldman_id between", value1, value2, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andOldmanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("oldman_id not between", value1, value2, "oldmanId");
            return (Criteria) this;
        }

        public Criteria andBackupIsNull() {
            addCriterion("backup is null");
            return (Criteria) this;
        }

        public Criteria andBackupIsNotNull() {
            addCriterion("backup is not null");
            return (Criteria) this;
        }

        public Criteria andBackupEqualTo(String value) {
            addCriterion("backup =", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupNotEqualTo(String value) {
            addCriterion("backup <>", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupGreaterThan(String value) {
            addCriterion("backup >", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupGreaterThanOrEqualTo(String value) {
            addCriterion("backup >=", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupLessThan(String value) {
            addCriterion("backup <", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupLessThanOrEqualTo(String value) {
            addCriterion("backup <=", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupLike(String value) {
            addCriterion("backup like", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupNotLike(String value) {
            addCriterion("backup not like", value, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupIn(List<String> values) {
            addCriterion("backup in", values, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupNotIn(List<String> values) {
            addCriterion("backup not in", values, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupBetween(String value1, String value2) {
            addCriterion("backup between", value1, value2, "backup");
            return (Criteria) this;
        }

        public Criteria andBackupNotBetween(String value1, String value2) {
            addCriterion("backup not between", value1, value2, "backup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 28 21:13:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldman_ruzhu
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}