package com.czp.project.common.bean;

import java.util.Date;

public class OldMan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.oldman_img
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String oldmanImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.oldman_name
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String oldmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.age
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.gender
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.birthday
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.checkintime
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Date checkintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.telphone
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.health
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.family_members_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Integer familyMembersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.room_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.user_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.old_number
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    private String oldNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.id
     *
     * @return the value of old_man.id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.id
     *
     * @param id the value for old_man.id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.oldman_img
     *
     * @return the value of old_man.oldman_img
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getOldmanImg() {
        return oldmanImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.oldman_img
     *
     * @param oldmanImg the value for old_man.oldman_img
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setOldmanImg(String oldmanImg) {
        this.oldmanImg = oldmanImg == null ? null : oldmanImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.oldman_name
     *
     * @return the value of old_man.oldman_name
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getOldmanName() {
        return oldmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.oldman_name
     *
     * @param oldmanName the value for old_man.oldman_name
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setOldmanName(String oldmanName) {
        this.oldmanName = oldmanName == null ? null : oldmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.age
     *
     * @return the value of old_man.age
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.age
     *
     * @param age the value for old_man.age
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.gender
     *
     * @return the value of old_man.gender
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.gender
     *
     * @param gender the value for old_man.gender
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.birthday
     *
     * @return the value of old_man.birthday
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.birthday
     *
     * @param birthday the value for old_man.birthday
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.checkintime
     *
     * @return the value of old_man.checkintime
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.checkintime
     *
     * @param checkintime the value for old_man.checkintime
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.telphone
     *
     * @return the value of old_man.telphone
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.telphone
     *
     * @param telphone the value for old_man.telphone
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.health
     *
     * @return the value of old_man.health
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.health
     *
     * @param health the value for old_man.health
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.family_members_id
     *
     * @return the value of old_man.family_members_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Integer getFamilyMembersId() {
        return familyMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.family_members_id
     *
     * @param familyMembersId the value for old_man.family_members_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setFamilyMembersId(Integer familyMembersId) {
        this.familyMembersId = familyMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.room_id
     *
     * @return the value of old_man.room_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.room_id
     *
     * @param roomId the value for old_man.room_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.user_id
     *
     * @return the value of old_man.user_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.user_id
     *
     * @param userId the value for old_man.user_id
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.old_number
     *
     * @return the value of old_man.old_number
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public String getOldNumber() {
        return oldNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.old_number
     *
     * @param oldNumber the value for old_man.old_number
     *
     * @mbg.generated Fri May 01 11:36:18 CST 2020
     */
    public void setOldNumber(String oldNumber) {
        this.oldNumber = oldNumber == null ? null : oldNumber.trim();
    }
}