package com.czp.project.common.bean;

public class OldMan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.oldman_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String oldmanImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.oldman_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String oldmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.idcard
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer familyMembersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.room_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.id
     *
     * @return the value of old_man.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.id
     *
     * @param id the value for old_man.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.oldman_img
     *
     * @return the value of old_man.oldman_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getOldmanImg() {
        return oldmanImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.oldman_img
     *
     * @param oldmanImg the value for old_man.oldman_img
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setOldmanImg(String oldmanImg) {
        this.oldmanImg = oldmanImg == null ? null : oldmanImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.oldman_name
     *
     * @return the value of old_man.oldman_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getOldmanName() {
        return oldmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.oldman_name
     *
     * @param oldmanName the value for old_man.oldman_name
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setOldmanName(String oldmanName) {
        this.oldmanName = oldmanName == null ? null : oldmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.idcard
     *
     * @return the value of old_man.idcard
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.idcard
     *
     * @param idcard the value for old_man.idcard
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.telphone
     *
     * @return the value of old_man.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.telphone
     *
     * @param telphone the value for old_man.telphone
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.family_members_id
     *
     * @return the value of old_man.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getFamilyMembersId() {
        return familyMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.family_members_id
     *
     * @param familyMembersId the value for old_man.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setFamilyMembersId(Integer familyMembersId) {
        this.familyMembersId = familyMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.room_id
     *
     * @return the value of old_man.room_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.room_id
     *
     * @param roomId the value for old_man.room_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man.user_id
     *
     * @return the value of old_man.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man.user_id
     *
     * @param userId the value for old_man.user_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}