package com.czp.project.common.bean;

import java.util.Date;

public class OldManRuZhu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.time
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.user_log
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private String userLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.in_room_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private String inRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.oldman_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private Integer oldmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_ruzhu.backup
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    private String backup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.id
     *
     * @return the value of oldman_ruzhu.id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.id
     *
     * @param id the value for oldman_ruzhu.id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.time
     *
     * @return the value of oldman_ruzhu.time
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.time
     *
     * @param time the value for oldman_ruzhu.time
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.user_log
     *
     * @return the value of oldman_ruzhu.user_log
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public String getUserLog() {
        return userLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.user_log
     *
     * @param userLog the value for oldman_ruzhu.user_log
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setUserLog(String userLog) {
        this.userLog = userLog == null ? null : userLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.in_room_id
     *
     * @return the value of oldman_ruzhu.in_room_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public String getInRoomId() {
        return inRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.in_room_id
     *
     * @param inRoomId the value for oldman_ruzhu.in_room_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setInRoomId(String inRoomId) {
        this.inRoomId = inRoomId == null ? null : inRoomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.oldman_id
     *
     * @return the value of oldman_ruzhu.oldman_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public Integer getOldmanId() {
        return oldmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.oldman_id
     *
     * @param oldmanId the value for oldman_ruzhu.oldman_id
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setOldmanId(Integer oldmanId) {
        this.oldmanId = oldmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_ruzhu.backup
     *
     * @return the value of oldman_ruzhu.backup
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public String getBackup() {
        return backup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_ruzhu.backup
     *
     * @param backup the value for oldman_ruzhu.backup
     *
     * @mbg.generated Tue Apr 28 21:13:01 CST 2020
     */
    public void setBackup(String backup) {
        this.backup = backup == null ? null : backup.trim();
    }
}