package com.czp.project.common.bean;

import java.util.ArrayList;
import java.util.List;

public class OldManExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public OldManExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOldmanImgIsNull() {
            addCriterion("oldman_img is null");
            return (Criteria) this;
        }

        public Criteria andOldmanImgIsNotNull() {
            addCriterion("oldman_img is not null");
            return (Criteria) this;
        }

        public Criteria andOldmanImgEqualTo(String value) {
            addCriterion("oldman_img =", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgNotEqualTo(String value) {
            addCriterion("oldman_img <>", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgGreaterThan(String value) {
            addCriterion("oldman_img >", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgGreaterThanOrEqualTo(String value) {
            addCriterion("oldman_img >=", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgLessThan(String value) {
            addCriterion("oldman_img <", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgLessThanOrEqualTo(String value) {
            addCriterion("oldman_img <=", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgLike(String value) {
            addCriterion("oldman_img like", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgNotLike(String value) {
            addCriterion("oldman_img not like", value, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgIn(List<String> values) {
            addCriterion("oldman_img in", values, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgNotIn(List<String> values) {
            addCriterion("oldman_img not in", values, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgBetween(String value1, String value2) {
            addCriterion("oldman_img between", value1, value2, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanImgNotBetween(String value1, String value2) {
            addCriterion("oldman_img not between", value1, value2, "oldmanImg");
            return (Criteria) this;
        }

        public Criteria andOldmanNameIsNull() {
            addCriterion("oldman_name is null");
            return (Criteria) this;
        }

        public Criteria andOldmanNameIsNotNull() {
            addCriterion("oldman_name is not null");
            return (Criteria) this;
        }

        public Criteria andOldmanNameEqualTo(String value) {
            addCriterion("oldman_name =", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameNotEqualTo(String value) {
            addCriterion("oldman_name <>", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameGreaterThan(String value) {
            addCriterion("oldman_name >", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameGreaterThanOrEqualTo(String value) {
            addCriterion("oldman_name >=", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameLessThan(String value) {
            addCriterion("oldman_name <", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameLessThanOrEqualTo(String value) {
            addCriterion("oldman_name <=", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameLike(String value) {
            addCriterion("oldman_name like", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameNotLike(String value) {
            addCriterion("oldman_name not like", value, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameIn(List<String> values) {
            addCriterion("oldman_name in", values, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameNotIn(List<String> values) {
            addCriterion("oldman_name not in", values, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameBetween(String value1, String value2) {
            addCriterion("oldman_name between", value1, value2, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andOldmanNameNotBetween(String value1, String value2) {
            addCriterion("oldman_name not between", value1, value2, "oldmanName");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNull() {
            addCriterion("idcard is null");
            return (Criteria) this;
        }

        public Criteria andIdcardIsNotNull() {
            addCriterion("idcard is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardEqualTo(String value) {
            addCriterion("idcard =", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotEqualTo(String value) {
            addCriterion("idcard <>", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThan(String value) {
            addCriterion("idcard >", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("idcard >=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThan(String value) {
            addCriterion("idcard <", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLessThanOrEqualTo(String value) {
            addCriterion("idcard <=", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardLike(String value) {
            addCriterion("idcard like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotLike(String value) {
            addCriterion("idcard not like", value, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardIn(List<String> values) {
            addCriterion("idcard in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotIn(List<String> values) {
            addCriterion("idcard not in", values, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardBetween(String value1, String value2) {
            addCriterion("idcard between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andIdcardNotBetween(String value1, String value2) {
            addCriterion("idcard not between", value1, value2, "idcard");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("telphone is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("telphone is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("telphone =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("telphone <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("telphone >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("telphone >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("telphone <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("telphone <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("telphone like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("telphone not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("telphone in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("telphone not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("telphone between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("telphone not between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdIsNull() {
            addCriterion("family_members_id is null");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdIsNotNull() {
            addCriterion("family_members_id is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdEqualTo(Integer value) {
            addCriterion("family_members_id =", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdNotEqualTo(Integer value) {
            addCriterion("family_members_id <>", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdGreaterThan(Integer value) {
            addCriterion("family_members_id >", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("family_members_id >=", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdLessThan(Integer value) {
            addCriterion("family_members_id <", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdLessThanOrEqualTo(Integer value) {
            addCriterion("family_members_id <=", value, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdIn(List<Integer> values) {
            addCriterion("family_members_id in", values, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdNotIn(List<Integer> values) {
            addCriterion("family_members_id not in", values, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdBetween(Integer value1, Integer value2) {
            addCriterion("family_members_id between", value1, value2, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andFamilyMembersIdNotBetween(Integer value1, Integer value2) {
            addCriterion("family_members_id not between", value1, value2, "familyMembersId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table old_man
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 29 13:12:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table old_man
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}