package com.czp.project.common.bean;

import java.util.Date;

public class OmQingjia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.start_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.end_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.state
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.oldman_id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Integer oldmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.user_log
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private String userLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.bakcup
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private String bakcup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_man_leave.reson
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    private String reson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.id
     *
     * @return the value of old_man_leave.id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.id
     *
     * @param id the value for old_man_leave.id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.start_time
     *
     * @return the value of old_man_leave.start_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.start_time
     *
     * @param startTime the value for old_man_leave.start_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.end_time
     *
     * @return the value of old_man_leave.end_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.end_time
     *
     * @param endTime the value for old_man_leave.end_time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.state
     *
     * @return the value of old_man_leave.state
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.state
     *
     * @param state the value for old_man_leave.state
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.oldman_id
     *
     * @return the value of old_man_leave.oldman_id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Integer getOldmanId() {
        return oldmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.oldman_id
     *
     * @param oldmanId the value for old_man_leave.oldman_id
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setOldmanId(Integer oldmanId) {
        this.oldmanId = oldmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.user_log
     *
     * @return the value of old_man_leave.user_log
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public String getUserLog() {
        return userLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.user_log
     *
     * @param userLog the value for old_man_leave.user_log
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setUserLog(String userLog) {
        this.userLog = userLog == null ? null : userLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.time
     *
     * @return the value of old_man_leave.time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.time
     *
     * @param time the value for old_man_leave.time
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.bakcup
     *
     * @return the value of old_man_leave.bakcup
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public String getBakcup() {
        return bakcup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.bakcup
     *
     * @param bakcup the value for old_man_leave.bakcup
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setBakcup(String bakcup) {
        this.bakcup = bakcup == null ? null : bakcup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_man_leave.reson
     *
     * @return the value of old_man_leave.reson
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public String getReson() {
        return reson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_man_leave.reson
     *
     * @param reson the value for old_man_leave.reson
     *
     * @mbg.generated Mon May 04 22:39:47 CST 2020
     */
    public void setReson(String reson) {
        this.reson = reson == null ? null : reson.trim();
    }
}