package com.czp.project.common.bean;

import java.util.Date;

public class OmWaichu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.event
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.stat_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private Date statTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.end_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.status
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.old_man_id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private Integer oldManId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.user_log
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private String userLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldman_waichu.backup
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    private String backup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.id
     *
     * @return the value of oldman_waichu.id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.id
     *
     * @param id the value for oldman_waichu.id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.event
     *
     * @return the value of oldman_waichu.event
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.event
     *
     * @param event the value for oldman_waichu.event
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.stat_time
     *
     * @return the value of oldman_waichu.stat_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public Date getStatTime() {
        return statTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.stat_time
     *
     * @param statTime the value for oldman_waichu.stat_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setStatTime(Date statTime) {
        this.statTime = statTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.end_time
     *
     * @return the value of oldman_waichu.end_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.end_time
     *
     * @param endTime the value for oldman_waichu.end_time
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.status
     *
     * @return the value of oldman_waichu.status
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.status
     *
     * @param status the value for oldman_waichu.status
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.old_man_id
     *
     * @return the value of oldman_waichu.old_man_id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public Integer getOldManId() {
        return oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.old_man_id
     *
     * @param oldManId the value for oldman_waichu.old_man_id
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setOldManId(Integer oldManId) {
        this.oldManId = oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.user_log
     *
     * @return the value of oldman_waichu.user_log
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public String getUserLog() {
        return userLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.user_log
     *
     * @param userLog the value for oldman_waichu.user_log
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setUserLog(String userLog) {
        this.userLog = userLog == null ? null : userLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldman_waichu.backup
     *
     * @return the value of oldman_waichu.backup
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public String getBackup() {
        return backup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldman_waichu.backup
     *
     * @param backup the value for oldman_waichu.backup
     *
     * @mbg.generated Sun May 03 21:17:17 CST 2020
     */
    public void setBackup(String backup) {
        this.backup = backup == null ? null : backup.trim();
    }
}