package com.czp.project.common.bean;

public class Pay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.money
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.cost_description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String costDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer oldManId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer familyMembersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.id
     *
     * @return the value of pay.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.id
     *
     * @param id the value for pay.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.money
     *
     * @return the value of pay.money
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.money
     *
     * @param money the value for pay.money
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.cost_description
     *
     * @return the value of pay.cost_description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getCostDescription() {
        return costDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.cost_description
     *
     * @param costDescription the value for pay.cost_description
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setCostDescription(String costDescription) {
        this.costDescription = costDescription == null ? null : costDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.old_man_id
     *
     * @return the value of pay.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getOldManId() {
        return oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.old_man_id
     *
     * @param oldManId the value for pay.old_man_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setOldManId(Integer oldManId) {
        this.oldManId = oldManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.family_members_id
     *
     * @return the value of pay.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getFamilyMembersId() {
        return familyMembersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.family_members_id
     *
     * @param familyMembersId the value for pay.family_members_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setFamilyMembersId(Integer familyMembersId) {
        this.familyMembersId = familyMembersId;
    }
}