package com.czp.project.common.bean;

public class UserLeave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_leave.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_leave.start_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_leave.end_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_leave.state
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_leave.user_manager_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    private Integer userManagerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_leave.id
     *
     * @return the value of user_leave.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_leave.id
     *
     * @param id the value for user_leave.id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_leave.start_time
     *
     * @return the value of user_leave.start_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_leave.start_time
     *
     * @param startTime the value for user_leave.start_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_leave.end_time
     *
     * @return the value of user_leave.end_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_leave.end_time
     *
     * @param endTime the value for user_leave.end_time
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_leave.state
     *
     * @return the value of user_leave.state
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_leave.state
     *
     * @param state the value for user_leave.state
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_leave.user_manager_id
     *
     * @return the value of user_leave.user_manager_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public Integer getUserManagerId() {
        return userManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_leave.user_manager_id
     *
     * @param userManagerId the value for user_leave.user_manager_id
     *
     * @mbg.generated Wed Jan 29 13:12:45 CST 2020
     */
    public void setUserManagerId(Integer userManagerId) {
        this.userManagerId = userManagerId;
    }
}